In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/breast-cancer-wisconsin-original/breast_cancer.csv


# Credits and Links

* UDEMY - Machine Learning A-Z <sup>TM</sup>*

<a id="index"></a>
# Table of Content

1. [Importing Libraries](#1)
2. [Importing Dataset](#2)
3. [Splitting the dataset into Train/Test](#3)
4. [Feature Scaling](#4)
5. [Random Forest Classifier](#5)
6. [Prediction](#6)
    - [New Result](#6.1)
    - [Test Result](#6.2)
7. [Confusion Matrix](#7)
6. [Visualization](#8)
    - [Training set results](#8.1)
    - [Test set results](#8.2)

<a id="1"></a>
# 1. Importing Libraries

[Go back to Index](#index)

In [2]:
#1. General
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
%matplotlib inline

#2. Data Preprocessing
##2.1 Fill Missing Data
from sklearn.impute import SimpleImputer

##2.2 Encoding
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

##2.3 Splitting Train and Test
from sklearn.model_selection import train_test_split

##2.4 Feature Scaling
from sklearn.preprocessing import StandardScaler

#3. Classifiers
##3.1 Logistic Regression
from sklearn.linear_model import LogisticRegression

##3.2 K Nearest Neighbours
from sklearn.neighbors import KNeighborsClassifier

##3.3 and 3.4 Support Vector Machine - SVM and Kernel
from sklearn.svm import SVC

##3.5 Naive Bayes
from sklearn.naive_bayes import GaussianNB

##3.6 Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier

#3.7 Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier

#4. Scikit Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score

<a id="2"></a>
# 2. Importing Dataset

[Go back to Index](#index)

In [3]:
# Dataset:= Combined Cycle Powerplant.csv
df = pd.read_csv('/kaggle/input/breast-cancer-wisconsin-original/breast_cancer.csv')
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

<a id="3"></a>
# 3. Splitting the dataset into Train/Test

[Go back to Index](#index)

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

<a id="4"></a>
# 4. Feature Scaling

[Go back to Index](#index)

In [5]:
sc = StandardScaler()

In [6]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

<a id="5"></a>
# 5. All Models

[Go back to Index](#index)

<a id="5.1"></a>
## 5.1 Logistic Regression

[Go back to Index](#index)

In [7]:
log_reg = LogisticRegression(random_state = 0)
log_reg.fit(X_train, y_train)

LogisticRegression(random_state=0)

<a id="5.2"></a>
## 5.2 KNN

[Go back to Index](#index)

In [8]:
knn_reg = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
knn_reg.fit(X_train, y_train)

KNeighborsClassifier()

<a id="5.3"></a>
## 5.3 Support Vector Machine

[Go back to Index](#index)

In [9]:
#SVM:= linearly separable models
svm_reg = SVC(kernel = 'linear', random_state = 0)
svm_reg.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

<a id="5.4"></a>
## 5.4 Kernel SVM

[Go back to Index](#index)

In [10]:
#Kernel SVM:= non-linearly separable models
ksvm_reg = SVC(kernel = 'rbf', random_state = 0)
ksvm_reg.fit(X_train, y_train)

SVC(random_state=0)

<a id="5.5"></a>
## 5.5 Naive Bayes

[Go back to Index](#index)

In [11]:
nb_reg = GaussianNB()
nb_reg.fit(X_train, y_train)

GaussianNB()

<a id="5.6"></a>
## 5.6 Decision Tree Classifier

[Go back to Index](#index)

In [12]:
dt_reg = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
dt_reg.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

<a id="5.7"></a>
## 5.7 Random Forest Classifier

[Go back to Index](#index)

In [13]:
rfc_reg = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
rfc_reg.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

<a id="6"></a>
# 6. Confusion Matrix and accuracy

[Go back to Index](#index)

<a id="6.1"></a>
## 6.1 Logistic Regression

[Go back to Index](#index)

In [14]:
y_pred_lr = log_reg.predict(X_test)
cm_lr = confusion_matrix(y_test, y_pred_lr)
print(cm_lr)
accuracy_score(y_test, y_pred_lr)

[[103   4]
 [  5  59]]


0.9473684210526315

In [15]:
df_lr = pd.DataFrame({"Model":["Logistic Regression"], "Score":[accuracy_score(y_test, y_pred_lr)]})
df_lr

Model     Score
0  Logistic Regression  0.947368

<a id="6.2"></a>
## 6.2 KNN

[Go back to Index](#index)

In [16]:
y_pred_knn = knn_reg.predict(X_test)
cm_knn = confusion_matrix(y_test, y_pred_knn)
print(cm_knn)
accuracy_score(y_test, y_pred_knn)

[[103   4]
 [  5  59]]


0.9473684210526315

In [17]:
df_knn = pd.DataFrame({"Model":["KNN"], "Score":[accuracy_score(y_test, y_pred_knn)]})
df_knn

Model     Score
0   KNN  0.947368

<a id="6.3"></a>
## 6.3 Support Vector Machine

[Go back to Index](#index)

In [18]:
y_pred_svm = svm_reg.predict(X_test)
cm_svm = confusion_matrix(y_test, y_pred_svm)
print(cm_svm)
accuracy_score(y_test, y_pred_svm)

[[102   5]
 [  5  59]]


0.9415204678362573

In [19]:
df_svm = pd.DataFrame({"Model":["SVM"], "Score":[accuracy_score(y_test, y_pred_svm)]})
df_svm

Model    Score
0   SVM  0.94152

<a id="6.4"></a>
## 6.4 Kernel SVM

[Go back to Index](#index)

In [20]:
y_pred_ksvm = ksvm_reg.predict(X_test)
cm_ksvm = confusion_matrix(y_test, y_pred_ksvm)
print(cm_ksvm)
accuracy_score(y_test, y_pred_ksvm)

[[102   5]
 [  3  61]]


0.9532163742690059

In [21]:
df_ksvm = pd.DataFrame({"Model":["Kernel SVM"], "Score":[accuracy_score(y_test, y_pred_ksvm)]})
df_ksvm

Model     Score
0  Kernel SVM  0.953216

<a id="6.5"></a>
## 6.5 Naive Bayes

[Go back to Index](#index)

In [22]:
y_pred_nb = nb_reg.predict(X_test)
cm_nb = confusion_matrix(y_test, y_pred_nb)
print(cm_nb)
accuracy_score(y_test, y_pred_nb)

[[99  8]
 [ 2 62]]


0.9415204678362573

In [23]:
df_nb = pd.DataFrame({"Model":["Naive Bayes"], "Score":[accuracy_score(y_test, y_pred_nb)]})
df_nb

Model    Score
0  Naive Bayes  0.94152

<a id="6.6"></a>
## 6.6 Decision Tree Classifier

[Go back to Index](#index)

In [24]:
y_pred_dt = dt_reg.predict(X_test)
cm_dt = confusion_matrix(y_test, y_pred_dt)
print(cm_dt)
accuracy_score(y_test, y_pred_dt)

[[103   4]
 [  3  61]]


0.9590643274853801

In [25]:
df_dt = pd.DataFrame({"Model":["Decision Tree"], "Score":[accuracy_score(y_test, y_pred_dt)]})
df_dt

Model     Score
0  Decision Tree  0.959064

<a id="6.7"></a>
## 6.7 Random Forest Classifier

[Go back to Index](#index)

In [26]:
y_pred_rfc = rfc_reg.predict(X_test)
cm_rfc = confusion_matrix(y_test, y_pred_rfc)
print(cm_rfc)
accuracy_score(y_test, y_pred_rfc)

[[102   5]
 [  6  58]]


0.935672514619883

In [27]:
df_rfc = pd.DataFrame({"Model":["Random Forest Classifier"], "Score":[accuracy_score(y_test, y_pred_rfc)]})
df_rfc

Model     Score
0  Random Forest Classifier  0.935673

In [28]:
df = pd.concat([df_lr, df_knn, df_svm, df_ksvm, df_dt, df_nb, df_rfc])
df = df.set_index("Model")
df

Score
Model                             
Logistic Regression       0.947368
KNN                       0.947368
SVM                       0.941520
Kernel SVM                0.953216
Decision Tree             0.959064
Naive Bayes               0.941520
Random Forest Classifier  0.935673

In [29]:
df[df["Score"]==df["Score"].max()]

Score
Model                  
Decision Tree  0.959064